-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE public.users
(
    id integer,
    email character varying(50),
    password character varying(25),
    PRIMARY KEY (id)
);

CREATE TABLE public.candidates
(
    candidate_id integer,
    name character varying(20),
    surname character varying(20),
    identity_number character varying(11),
    birth_date date,
    "isActivated" boolean,
    PRIMARY KEY (candidate_id)
);

CREATE TABLE public.employers
(
    employer_id integer,
    company_name character varying(50),
    website character varying(50),
    email character varying(50),
    phone_number character varying(12),
    PRIMARY KEY (employer_id)
);

CREATE TABLE public.personnel
(
    personnel_id integer,
    name character varying(20),
    surname character varying(20),
    PRIMARY KEY (personnel_id)
);

CREATE TABLE public.authorized_personnel
(
    auth_id "char",
    is_authorized boolean,
    aauthorized_sector integer[],
    PRIMARY KEY (auth_id)
);

CREATE TABLE public.job_titles
(
    job_id integer,
    job_detail character varying(100),
    employers_id integer,
    job_sector integer,
    PRIMARY KEY (job_id)
);

CREATE TABLE public.employers_activation
(
    id integer,
    activation_hrms boolean,
    activation_email boolean,
    all_confirmation_date date,
    PRIMARY KEY (id)
);

CREATE TABLE public.candidates_activation
(
    id integer,
    email_activation boolean,
    activation_status boolean,
    PRIMARY KEY (id)
);

ALTER TABLE public.users
    ADD FOREIGN KEY (id)
    REFERENCES public.candidates (candidate_id)
    NOT VALID;


ALTER TABLE public.users
    ADD FOREIGN KEY (id)
    REFERENCES public.employers (employer_id)
    NOT VALID;


ALTER TABLE public.users
    ADD FOREIGN KEY (id)
    REFERENCES public.personnel (personnel_id)
    NOT VALID;


ALTER TABLE public.personnel
    ADD FOREIGN KEY (personnel_id)
    REFERENCES public.authorized_personnel (auth_id)
    NOT VALID;


ALTER TABLE public.job_titles
    ADD FOREIGN KEY (employers_id)
    REFERENCES public.employers (employer_id)
    NOT VALID;


ALTER TABLE public.employers
    ADD FOREIGN KEY (employer_id)
    REFERENCES public.employers_activation (id)
    NOT VALID;


ALTER TABLE public.candidates
    ADD FOREIGN KEY ("isActivated")
    REFERENCES public.candidates_activation (activation_status)
    NOT VALID;

END;